services:
  app:
    build:
      context: ./develop
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/
    ports:
      - 9000:80
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: to-camp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # volumes:
    #   - to-camp-db-volume:/var/lib/mysql
  mysql_test:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: to-camp-test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
